-- Jalankan seluruh file ini di Supabase Dashboard > SQL Editor.
-- Skema ini menyimpan perjalanan dan booking Bustara dengan RLS aktif.

create extension if not exists pgcrypto;

create table if not exists public.trips (
  id bigint generated by default as identity primary key,
  operator text not null check (char_length(operator) between 2 and 100),
  type text not null check (type in ('Bus Biasa', 'Sleeper')),
  from_city text not null check (char_length(from_city) between 2 and 100),
  to_city text not null check (char_length(to_city) between 2 and 100),
  depart time not null,
  arrive time not null,
  duration text not null check (char_length(duration) between 2 and 30),
  price integer not null check (price > 0),
  rating numeric(2, 1) not null check (rating between 0 and 5),
  amenities text[] not null default '{}',
  created_at timestamptz not null default now(),
  unique (from_city, to_city, type)
);

create table if not exists public.bookings (
  id uuid primary key default gen_random_uuid(),
  code text not null unique check (code ~ '^BTR-[A-Z0-9]{5}$'),
  route text not null check (char_length(route) between 5 and 255),
  passenger text not null check (char_length(passenger) between 2 and 255),
  email text not null check (char_length(email) between 5 and 255),
  phone text not null check (char_length(phone) between 6 and 32),
  seats text[] not null check (cardinality(seats) > 0),
  travel_date date not null,
  total integer not null check (total > 0),
  created_at timestamptz not null default now()
);

create index if not exists bookings_created_at_idx on public.bookings (created_at desc);
create index if not exists bookings_travel_date_idx on public.bookings (travel_date);

alter table public.trips enable row level security;
alter table public.bookings enable row level security;

-- Hanya perjalanan yang bersifat publik yang dapat dibaca dari browser.
revoke all on table public.trips from anon, authenticated;
grant select on table public.trips to anon, authenticated;
drop policy if exists "Perjalanan dapat dibaca publik" on public.trips;
create policy "Perjalanan dapat dibaca publik"
on public.trips for select
to anon, authenticated
using (true);

-- Pengunjung dapat membuat booking, tetapi tidak dapat membaca, mengubah,
-- atau menghapus data penumpang melalui API publik.
revoke all on table public.bookings from anon, authenticated;
grant insert on table public.bookings to anon, authenticated;
drop policy if exists "Pengunjung dapat membuat booking" on public.bookings;
create policy "Pengunjung dapat membuat booking"
on public.bookings for insert
to anon, authenticated
with check (
  travel_date >= current_date - 1
  and cardinality(seats) <= 10
);

insert into public.trips
  (id, operator, type, from_city, to_city, depart, arrive, duration, price, rating, amenities)
values
  (1, 'Litha & Co', 'Bus Biasa', 'Makassar', 'Selayar', '08:00', '13:30', '5j 30m', 250000, 4.7, array['AC', 'USB', 'Recliner']),
  (2, 'Bintang Timur', 'Sleeper', 'Makassar', 'Selayar', '20:00', '01:30', '5j 30m', 300000, 4.9, array['AC', 'WiFi', 'Bed Seat']),
  (3, 'Litha & Co', 'Bus Biasa', 'Selayar', 'Makassar', '08:00', '13:30', '5j 30m', 250000, 4.7, array['AC', 'USB', 'Recliner']),
  (4, 'Bintang Timur', 'Sleeper', 'Selayar', 'Makassar', '20:00', '01:30', '5j 30m', 300000, 4.9, array['AC', 'WiFi', 'Bed Seat']),
  (5, 'Litha & Co', 'Bus Biasa', 'Makassar', 'Toraja', '08:00', '13:30', '8j 00m', 200000, 4.7, array['AC', 'USB', 'Recliner']),
  (6, 'Bintang Timur', 'Sleeper', 'Makassar', 'Toraja', '20:00', '01:30', '8j 00m', 250000, 4.9, array['AC', 'WiFi', 'Bed Seat']),
  (7, 'Litha & Co', 'Bus Biasa', 'Toraja', 'Makassar', '08:00', '13:30', '8j 00m', 200000, 4.7, array['AC', 'USB', 'Recliner']),
  (8, 'Bintang Timur', 'Sleeper', 'Toraja', 'Makassar', '20:00', '01:30', '8j 00m', 250000, 4.9, array['AC', 'WiFi', 'Bed Seat']),
  (9, 'Litha & Co', 'Bus Biasa', 'Makassar', 'Palopo', '08:00', '13:30', '9j 15m', 350000, 4.7, array['AC', 'USB', 'Recliner']),
  (10, 'Bintang Timur', 'Sleeper', 'Makassar', 'Palopo', '20:00', '01:30', '9j 15m', 400000, 4.9, array['AC', 'WiFi', 'Bed Seat']),
  (11, 'Litha & Co', 'Bus Biasa', 'Palopo', 'Makassar', '08:00', '13:30', '9j 15m', 350000, 4.7, array['AC', 'USB', 'Recliner']),
  (12, 'Bintang Timur', 'Sleeper', 'Palopo', 'Makassar', '20:00', '01:30', '9j 15m', 400000, 4.9, array['AC', 'WiFi', 'Bed Seat'])
on conflict (id) do update set
  operator = excluded.operator,
  type = excluded.type,
  from_city = excluded.from_city,
  to_city = excluded.to_city,
  depart = excluded.depart,
  arrive = excluded.arrive,
  duration = excluded.duration,
  price = excluded.price,
  rating = excluded.rating,
  amenities = excluded.amenities;

select setval(pg_get_serial_sequence('public.trips', 'id'), (select max(id) from public.trips));
